name = "game2048"
main = "worker/index.ts"
compatibility_date = "2025-09-30"

[[d1_databases]]
binding = "DB"
database_name = "game2048-db"
database_id = "REPLACE_WITH_YOUR_DB_ID"

[vars]
JWT_SECRET = "super_secret_key"
